site_name: 探究vits不同数据集对合成效果以及微调的效果的影响

theme:
  name: material
  features:
    - content.tabs

nav:
  - 不同数据vits合成效果对比: index.md
  - 微调效果对比: index2.md
  - unclean合成效果对比: index3.md
  # 在这里添加更多页面，如果需要

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lunar333/vits-japanese-finetune.git